services:
  e2e-test-runner:
    build: ./e2e
    environment:
      - DIFFICALCY_PERFORMANCEPLUS_HOST=difficalcy-performanceplus:80
    depends_on:
      - difficalcy-performanceplus

  beatmap-server:
    image: caddy:2-alpine
    volumes:
      - ./e2e/beatmaps:/usr/share/caddy:ro

  difficalcy-performanceplus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - BEATMAP_DOWNLOAD_URL=http://beatmap-server:80/{beatmapId}.osu
    depends_on:
      - beatmap-server
