#!/bin/bash
set -euxo pipefail

hosts=("$DIFFICALCY_HOST" "${DIFFICALCY_SLIM_HOST:-}")

for host in "${hosts[@]}"; do
  [ -z "$host" ] && continue
  echo "=== Testing $host ==="
  API="http://$host/api/calculators"

  curl --fail --silent --show-error "$API" | jq

  curl --fail --silent --show-error "$API/osu/info" | jq
  curl --fail --silent --show-error "$API/osu/calculation?BeatmapId=diffcalc-test" | jq
  curl --fail --silent --show-error "$API/osu/calculation?BeatmapId=diffcalc-test" | jq
  curl --fail --silent --show-error "$API/osu/calculation?BeatmapId=diffcalc-test&Mods=HD,DT" | jq
  curl --fail --silent --show-error -X POST "$API/osu/batch/calculation" \
    -H "Content-Type: application/json" \
    -d '[{"BeatmapId": "diffcalc-test"}, {"BeatmapId": "diffcalc-test", "Mods": [{"Acronym": "DT"}]}]' | jq
  curl --fail --silent --show-error "$API/osu/beatmapdetails?BeatmapId=diffcalc-test" | jq
done
