name: create-new-release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
        default: "v0.0.0-alpha.0"
        type: string
      prerelease:
        description: "Create as pre-release"
        required: false
        default: false
        type: boolean

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - name: Release
        if: ${{ !inputs.prerelease }}
        run: make release VERSION=${{ inputs.version }} GITHUB_USERNAME=${{ github.actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pre-release
        if: ${{ inputs.prerelease }}
        run: make pre-release VERSION=${{ inputs.version }} GITHUB_USERNAME=${{ github.actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
